# @package _global_
model:
  name: one_hot
  _target_: src.models.causal_tft.tft_causal.CausalTFT
  params:
    treatment_module_class: src.models.causal_tft.treatment_encoder.OneHotTreatmentModule
    treatment_max_value: 2
    weight_decay: 1e-2
  theta_params:
    weight_decay: 1e-2
    learning_rate: 1e-4

exp:
  max_epochs: 15
  theta_max_epochs: 10

defaults:
  - baseline.yaml
  - _self_